### ISSUE TITLE
Setting up with default ember-cli-deploy-build

### ISSUE THREAD

**Issue by dehuszar** [martinic/ember-cli-deploy-couchdb#20]
How would I go about getting this plugin working with the regular ember-cli-deploy build plugin?  I've seen the discussion on the [main plugin's issues thread](https://github.com/ember-cli-deploy/ember-cli-deploy-build/pull/23#issuecomment-159483390) but I'd really rather do the configuration myself than use a forked plugin.

Is it just passing some context-assembled path for attachments to the distDir property?  Or are there other details involved?

**Comment by broerse** [comment]
As long as setting a var in the configuration will make it read-only you could set outputPath, couchDir and distDir to:

```
    outputPath: 'tmp/deploy-dist/_attachments',
    couchDir: 'tmp/deploy-dist',
    distDir: 'tmp/deploy-dist/_attachments'
```

and use the regular deploy. The plus version does this for you and it provides an ENV specific robots.txt file for staging.

**Comment by broerse** [comment]
Perhaps use `path.sep` to support windows and linux.

**Comment by dehuszar** [comment]
Thanks!!

I think I've gotten most of the way there.  I am able to successfully deploy to my development couch server.  And when I go to my site's design document, I get a ton of output, but I'm not actually able to see the site render.  I've traditionally just hosted the ember side via nginx, so forgive me if I'm missing something super obvious, but what URL should I be able to go to to see my ember site actually get rendered?  Every path I try, to the extent that it exists just returns json.

Here's a gist of my [deploy.js config](https://gist.github.com/dehuszar/8ed7d9e7739536ef6b1a).

**Comment by broerse** [comment]
Sorry! I think you have to set `outputPath:` on the regular deploy environment to `tmp/deploy-dist/_attachments` .I don't have time to check now.

**Comment by dehuszar** [comment]
Unless I'm not understanding what you mean by regular deploy environment, outputPath is set as described.  Should I be able to see my Ember interface by going to http://0.0.0.0:5984/couch_db_name?

**Comment by broerse** [comment]
It is why I had to build [ember-cli-build-plus](https://github.com/martinic/ember-cli-deploy-build-plus) :smile: 

You need to set ENV.build `outputPath:` to `tmp/deploy-dist/_attachments` and ENV.couchdb `distDir:` to `tmp/deploy-dist/_attachments`  and ENV.couchdb `couchDir:` to `tmp/deploy-dist` 

But I can create a working version with the regular build if you don't get it to work. The baseURL you need to visit without a vhost is something like this `http://0.0.0.0:5984/emberapp/_design/ddocname/_rewrite/'` I print the correct baseURL to the screen when you run deploy.

**Comment by dehuszar** [comment]
So after [implementing the change you mentioned](https://gist.github.com/dehuszar/8ed7d9e7739536ef6b1a), I get the following error:

```
TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at Class.DeployPluginBase.extend.didBuild (/home/dehuszar/Development/resume-builder/node_modules/ember-cli-deploy-couchdb/index.js:54:16)
    at Object._pipeline.register.fn (/home/dehuszar/Development/resume-builder/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:175:21)
    at Pipeline._notifyPipelinePluginHookExecution (/home/dehuszar/Development/resume-builder/node_modules/ember-cli-deploy/lib/models/pipeline.js:136:19)
    at lib$rsvp$$internal$$tryCatch (/home/dehuszar/Development/resume-builder/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/home/dehuszar/Development/resume-builder/node_modules/rsvp/dist/rsvp.js:505:17)
    at /home/dehuszar/Development/resume-builder/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/home/dehuszar/Development/resume-builder/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickCallback (node.js:385:13)Pipeline aborted
```

There's one other thing that I find confusing in the docs, which may or may not be related.  Is the /emberapp/ segment a fixed label, meaning it _must_ read emberapp?  Because it reads like it should be an alias for the couchDB database.  Additionally, ddocname appears to be a variable which defaults to the project name even though the /ddocname/ segment of the various urls doesn't appear to be a variable

**Comment by dehuszar** [comment]
Quick update.  Looks like my .env.deploy.[ENV] files got blown away somehow and that was causing the error.  I am now able to push to my CouchDB server and load the site.  But I am not able to get my image files to load on the site.  They return 404 errors.  The target paths are just normal paths; i.e. `/images/[subfolder/filename.ext]` and work on my local EmberCLI + PouchDB instance.  Is there anything missing or out of place in [my gist](https://gist.github.com/dehuszar/8ed7d9e7739536ef6b1a) that might cause this issue?

**Comment by broerse** [comment]
Your gist looks fine to me. Do you see the images in `tmp/deploy-dist/_attachments` ? Is this in you `tmp/deploy-dist/rewites.json`?

```
  {
    "from": "images/*",
    "to": "images/*",
    "method": "GET"
  },
```

**Comment by broerse** [comment]
sub sub folders work for me? 

http://bloggr.exmer.com/tttt/vvvv/668160_34579120-be484908c29543cc3354be91920f4acd.jpg

**Comment by broerse** [comment]
Perhaps you images are addressed absolute. They need to be relative to the `<base href="/resume_builder/_design/resume-builder/_rewrite/" />` in the index.html file generated by ember-cli. `/images/[subfolder/filename.ext]` needs to be `images/[subfolder/filename.ext]` ??? Or use a CouchDB vhost.

**Comment by dehuszar** [comment]
Woot!  Setting the images to "images/etc/" instead of "/images/etc/" did the trick.  Thank you for your help with this!

I think it would really be worth putting a clear example together for folks who wanted to use the regular cli-deploy library.  I don't think the configuration is that onerous once it's laid out plainly.  I would be happy to put together a PR against the docs if you're interested.

**Comment by broerse** [comment]
@dehuszar Yes please write the PR.  It would be nice if there is a choice between [ember-cli-deploy-build](https://github.com/ember-cli-deploy/ember-cli-deploy-build) and [ember-cli-deploy-build-plus](https://github.com/martinic/ember-cli-deploy-build-plus). Perhaps address the `/` `\` issue for windows or use `path.sep` (`path = require('path');`) in your example.

**Comment by dehuszar** [comment]
Cool.  I'm trying to get the last piece in place for my application.  I've set up an account at cloudant.com, and tried to model my production environment settings to be like the ember-cli-blog example, but running `ember deploy production` yields the following error: (with my project folder structure ripped out)
```
Error: ENOENT: no such file or directory, open 'undefined/_id'
Error: ENOENT: no such file or directory, open 'undefined/_id'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at Class.DeployPluginBase.extend.didBuild ([path-to-app]/node_modules/ember-cli-deploy-couchdb/index.js:93:12)
    at Object._pipeline.register.fn ([path-to-app]/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:175:21)
    at Pipeline._notifyPipelinePluginHookExecution ([path-to-app]/node_modules/ember-cli-deploy/lib/models/pipeline.js:136:19)
    at lib$rsvp$$internal$$tryCatch ([path-to-app]/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback ([path-to-app]/node_modules/rsvp/dist/rsvp.js:505:17)
    at [path-to-app]/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush ([path-to-app]/node_modules/rsvp/dist/rsvp.js:1198:9)Pipeline aborted
```

Is there anything else build-plus does in the background, or might I just be missing a piece from my config?  I've updated [the gist](https://gist.github.com/dehuszar/8ed7d9e7739536ef6b1a) to match my current config.

**Comment by broerse** [comment]
Merged https://github.com/martinic/ember-cli-deploy-couchdb/pull/40
